# Subjective Assignment - 5 - Numpy

In [1]:
#Q1. Write the NumPy program to create a 2d array with 6 on the border and 0 inside?

In [2]:
import numpy as np 

a= 6*( np.ones((5,5)))
print("Expected OutputOriginal array-")
print(a)
a[1:-1,1:-1] = 0
print("6 on the border and 0 inside")
print(a)

Expected OutputOriginal array-
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
6 on the border and 0 inside
[[6. 6. 6. 6. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 0. 0. 0. 6.]
 [6. 6. 6. 6. 6.]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the checkerboard pattern?

In [3]:


b= 9*( np.ones((8,8)))
print("Checkerboard pattern")
b[0::2,0::2] =3
b[1::2,1::2] =3
print(b)



Checkerboard pattern
[[3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]
 [3. 9. 3. 9. 3. 9. 3. 9.]
 [9. 3. 9. 3. 9. 3. 9. 3.]]


Q3. Write the NumPy program to create an empty and a full array

In [4]:
x = np.empty((3,4))
print(x)

y = np.full((3,3),6)
print(y)

[[5.63e-322 0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 0.00e+000 0.00e+000]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade degrees into the Fahrenheit degrees and the centigrade values are stored in the NumPy array.

In [5]:
F = np.array ([0, 12, 45.21 ,34, 99.91])
print(F)
print("Values in Centigrade")
print((5*F-32)/9)

[ 0.   12.   45.21 34.   99.91]
Values in Centigrade
[-3.55555556  3.11111111 21.56111111 15.33333333 51.95      ]


Q5. Write the NumPy program to find the real and imaginary parts of an array of complex numbers?

In [6]:

Z = np.array([1.00000000+0.j,0.70710678+0.70710678j])



print("Real part of the array:")
print(Z.real)
print("Imaginary part of the array")
print(Z.imag)


Real part of the array:
[1.         0.70710678]
Imaginary part of the array
[0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D array is also present in the second array?

In [7]:
array1 = np.array([0, 10, 20, 40, 60])

array2 = [0, 40]

print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))

Compare each element of array1 and array2
[ True False False  True False]


Q7. Write the NumPy program to find common values between two arrays?

In [8]:
array1 = np.array([0, 10, 20, 40, 60])

array2 = [10, 30, 40]

print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Common values between two arrays:
[10 40]


Q8. Write the NumPy program to get the unique elements of an array?

In [9]:
x = np.array([10, 10, 20, 20, 30, 30])


print(np.unique(x))
o = np.array([[1, 1], [2, 3]])

print(np.unique(o))

[10 20 30]
[1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays?

In [10]:
arr1 = np.array([0, 10, 20,40, 60, 80])
arr2 = np.array ([10, 30, 40, 50, 70])
ab = np.setxor1d(arr1,arr2)
print(ab)

[ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array evaluate to True ?

In [11]:
x1 = print(np.all([10,20,0]))

False


Q11. Write the NumPy program to test whether any array element along the given axis evaluates to True?

In [12]:
x2 = print(np.any([10,20,50]))

True


Q12. Write the NumPy program to construct an array by repeating?

In [13]:
c1 = np.array([1,2,3,4])
print("Repaeating 2 times")
print(np.tile(c1,2))
print("Repaeating 3 times")
print(np.tile(c1,3))

Repaeating 2 times
[1 2 3 4 1 2 3 4]
Repaeating 3 times
[1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and minimum values with the given axis of an array?

In [14]:
c2 = np.array([1,2,3,4,5,6])
print(np.argmax(c2))
print(np.argmin(c2))


5
0


Q14. Write the NumPy program compare two arrays using numpy?

In [15]:
a = np.array([1, 2])
b = np.array([4, 5])
print("Array a: ",a)
print("Array b: ",b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))

Array a:  [1 2]
Array b:  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an array?

In [20]:
ab = np.array([[2,5],[4, 4]])

print(ab)
print("Sort along the first axis: ")
x = np.sort(ab, axis=0)
print(x)
print("Sort along the last axis: ")
y = np.sort(x, axis=1)
print(y)

[[2 5]
 [4 4]]
Sort along the first axis: 
[[2 4]
 [4 5]]
Sort along the last axis: 
[[2 4]
 [4 5]]


#Q16. Write the NumPy program to sort pairs of first name and last name return their indices (first by last name, then by first name).

first_names = np.array([Betsey, Shelley, Lanell, Genesis, Margery ])
last_names = np.array([ Battle, Brien, Plotner, Stahl, Woolum ])

Q17. Write the NumPy program to get the values and indices of the elements that are bigger than 10 in the given array?

In [18]:
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy array?

In [25]:
n = np.zeros((2,4))
print("%d bytes" % (n.size* n.itemsize))

64 bytes
